# config/local.yaml

env: "local" # Окружение - local, dev или prod
storage_path: "postgres://postgres:postgres@localhost:5432/banner-service" # файл, в котором будет храниться наша БД
http_server: # конфигурация нашего http-сервера
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 30s
signingKey: "6902747436:AAHVNZl6eVSt6Y0YzRVaDEdFSa5A-X4e7oI"

